name: Contexti
run-name: Â¡Estoy aprendiendo a usar Contextos!
on:
  push
jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    run-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF en el repositorio ${{ github.repository }}"